' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by SpecFlow (http://www.specflow.org/).
'      SpecFlow Version:1.3.5.2
'      Runtime Version:4.0.30319.1
' 
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------
#Region "Designer generated code"
Imports TechTalk.SpecFlow

Namespace SpecFlowDemo.AcceptanceTests.Features


    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2"),
    System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
    Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()>
    Partial Public Class RegisterANewSiteUserFeature

        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner

        <Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()>
        Public Shared Sub FeatureSetup(ByVal testContext As Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner()
            Dim featureInfo As New TechTalk.SpecFlow.FeatureInfo(
                New System.Globalization.CultureInfo("en-US"),
                "Register a new site user",
                "In order to view customer information" & vbCrLf &
                "As a new site user" & vbCrLf &
                "I want to be able to r" & "egister for a new account",
                (CType(Nothing, String())))
            testRunner.OnFeatureStart(featureInfo)
        End Sub

        <Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()>
        Public Shared Sub FeatureTearDown()
            testRunner.OnFeatureEnd()
            testRunner = Nothing
        End Sub

        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub

        <Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()>
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd()
        End Sub

        <Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(),
        Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Register with valid information"),
        Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Register a new site user")>
        Public Overridable Sub RegisterWithValidInformation()
            Dim scenarioInfo As New TechTalk.SpecFlow.ScenarioInfo("Register with valid information",
                                                                   (CType(Nothing, String())))

            Me.ScenarioSetup(scenarioInfo)

            testRunner.Given("I am on the site home page")

            testRunner.When("I click the ""Log On"" link")

            testRunner.And("I click the ""Register"" link")

            testRunner.And("I enter a random username")

            Dim table1 As New TechTalk.SpecFlow.Table(New String() {"Field", "Value"})
            table1.AddRow(New String() {"Email", "msdnuser@live.com"})
            table1.AddRow(New String() {"Password", "password"})
            table1.AddRow(New String() {"ConfirmPassword", "password"})

            testRunner.And("I complete the form with the following information:", (CStr(Nothing)), table1)

            testRunner.And("I click the ""Register"" button")

            testRunner.Then("I should see a link with the text ""Log Off"" on the page")

            testRunner.CollectScenarioErrors()
        End Sub
    End Class
End Namespace
#End Region
